### ISSUE TITLE
Should have unit tests for particle.js

### ISSUE THREAD

**Issue by gilhooley** [unexpected-lion/ourglass#41]

**Comment by gilhooley** [comment]
Working on this today

**Comment by johnheroy** [comment]
I guess we can do something trivial like test for gravity like it moves more quickly later on, and that it is not in the same place as the last step if there is a collision, but I would imagine we will continue to refine our Physics so it's not perfect right now

**Comment by johnheroy** [comment]
Actually just realized--these are unit tests and the collision handler is in the Player not Particle class. So let's not include collision detection in the Particle unit tests (but still do gravity)
