### ISSUE TITLE
particles should delete themselves at the min/max Y

### ISSUE THREAD

**Issue by NickStefan** [unexpected-lion/ourglass#49]

**Comment by johnheroy** [comment]
I found this today while working, I think you can use `this.c.renderer._viewSize.x` and `this.c.renderer._viewSize.y` to get the canvas dimensions while in the Particle or Player classes

**Comment by NickStefan** [comment]
working on it as we speak. I was going to sort of take an approach similar to your getMinX with the player

**Comment by johnheroy** [comment]
cool sounds good :+1:

**Comment by NickStefan** [comment]
when particles reach bottom, they reset to Y=0, in the future they can reset to spout. particles that reach the goal bucket disappear (but increment score).
